### ISSUE TITLE
a complete UI Kit with all system elements

### ISSUE THREAD

**Issue by alexkaessner** [alexkaessner/macOS-UI-Kit#1]
The current version only includes the most important UI elements. I'm thinking about making a full macOS Sierra UI Kit with all UI elements, a Sketch template and so on.

Would you like to see something like this?

Show me a reaction if you are interested in a bigger update. 👍 

**Edit: I'm planing to release the full kit with the coming High Sierra update…for more details take a look at the [project](https://github.com/alexkaessner/macOS-UI-Kit/projects/1)**.

**Comment by TofPlay** [comment]
Hi Alex 😀
> Would you like to see something like this?
Yes for sure!

> Show me a reaction if you are interested in a bigger update. 👍
I do not know the exact number but I heard that we are several million developers on iOS. 
And I think we are more to be interested in the development of applications for macOS. But without a good UI Kit for macOS is quite difficult.

**Comment by mykebates** [comment]
[A thousand times YES](https://quipvid.com/watch/sp6efoqz)

**Comment by Srini93** [comment]
**Would be glad** to have the complete UI kit for the touchbar ! 👍

**Comment by jariz** [comment]
Yes! Would also love to see a dark variant of all components, if possible.

**Comment by stephenolmstead** [comment]
Dig the Craft Library support, thanks for that! Can we get the touch bar assets added to the Craft Library file as well?

**Comment by alexkaessner** [comment]
**First of all thanks for all the feedback!** Glad you're interested in a full UI Kit! Keep the thumbs up and share it with your friends. 👍
I'm planning to do this thing one time, but I have no timeline yet.

For now I'm focusing on the new Touch Bar. I'm already working on the next update here.
So yes @stephenolmstead, if I have all UI elements together I will create a Craft Library again!

**Comment by milesfitzgerald** [comment]
Yes!!!

**Comment by staniki** [comment]
thanks dude, great job :) just do it!

**Comment by mabadir** [comment]
Yes for sure 👍 
😊

**Comment by Glitched** [comment]
Please keep working on it! It's great so far!

**Comment by inspiredmac** [comment]
Yes, your terrific work is greatly appreciated.

**Comment by JohnKis** [comment]
👍

**Comment by alexkaessner** [comment]
I’m closing this issue in favor of the new [2.0 release](https://github.com/alexkaessner/macOS-UI-Kit/releases/tag/v2.0) and the [new place to suggest elements](https://github.com/alexkaessner/macOS-UI-Kit/discussions). Thanks for your support everyone!
