### ISSUE TITLE
Version with Affinity Designer

### ISSUE THREAD

**Issue by TofPlay** [alexkaessner/macOS-UI-Kit#2]
Hi Alexander,
You should take a look of [Affinity Designer v1.5](https://goo.gl/i5FK5Q)
[![image](https://cloud.githubusercontent.com/assets/1082222/19393127/b6d1db8e-9233-11e6-8fb2-729ccdebe083.png)](https://goo.gl/i5FK5Q)
A version of your UI Kit with Affinity Designer will be fantastic 😉

**Comment by alexkaessner** [comment]
Thanks for the suggestion! As with #1 show guys some +1 if you want this too!

I've added this to the complete UI Kit Project, to keep track of this! Who knows maybe sometime this thing will happen. 😉

**Comment by alexkaessner** [comment]
Hi, I’m closing this issue now, as an Affinity version of this library is not realistic within a reasonable scale. It’s just too much to maintain for me alone. I’m very open for contribution if you or someone else is interested to team up. Let me know!
