### ISSUE TITLE
Autolayout with Sketch 😉

### ISSUE THREAD

**Issue by TofPlay** [alexkaessner/macOS-UI-Kit#5]
For you next Sketch file you should use Autolayout.
Take a look at this video: [Auto Layout Plugin for Sketch App](https://www.youtube.com/watch?v=v393LgriWCs)

**Comment by alexkaessner** [comment]
I see this as completed with the latest Sketch 44 autolayout function. I've updated the file using the new in-house function: f9d27788d59e54d2510e54d6c9d7283919d2b356
